Add proper pre-check job

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,11 +37,17 @@ jobs:
       with:
         category: "/language:go"
 
-  pre-checks:
-    name: Pre-Checks
+  pre-check:
+    name: Pre-checks Passed
     runs-on: ubuntu-latest
     needs: [build-scan]
+    if: always()
     steps:
-      - name: All checks successful
-        if: contains(needs.*.result,'success')
-        run: echo "success!"
+      - run: |
+          if [ ${{ contains(needs.*.result, 'failure') }} = 'true' ]; then
+            echo "At least one of the checks failed!"
+            exit 1
+          fi
+          echo "Success!"
+
+
